# Generated by Django 3.0 on 2020-04-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postSlug',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
