# Generated by Django 3.0 on 2020-04-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_postslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postSlug',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
