# Generated by Django 3.0 on 2020-05-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200510_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='comment',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
    ]
